# Generated by Django 4.0.5 on 2022-09-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
