# Generated by Django 4.0.5 on 2022-09-27 06:45

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('progress', models.IntegerField(help_text='Number from 10 to 100 in increments of 10', validators=[portfolio.models.validate_progress])),
            ],
        ),
    ]
