# Generated by Django 4.0.5 on 2022-10-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skillsbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=500)),
                ('about_profession', models.CharField(max_length=500)),
                ('resume_file', models.FileField(upload_to='')),
                ('about_skills', models.CharField(max_length=500)),
                ('about_portfolio', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skillsbar',
            options={'ordering': ['-progress']},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='about_project',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
