# Generated by Django 4.0.5 on 2022-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolioproject_about_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='my_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
